Feature/input
peaksoft-school/health-check-js11 pull request #10
Opened 2024-01-11 14:56 UTC by Nuranazm

feature input

2024-01-14 06:35 UTC, AziatAbd requested changes

2024-01-14 06:35 UTC, AziatAbd commented on src/components/UI/Input/Input.jsx
> +      '&.css-9ddj71-MuiInputBase-root-MuiOutlinedInput-root.Mui-disabled .MuiOutlinedInput-notchedOutline ':
этот стиль не будет работать

2024-01-14 06:35 UTC, AziatAbd commented on src/components/UI/Input/Input.jsx
> +      { value, onChange, placeholder, invalid, error, type = 'text', ...rest },
для чего нужен invalid?

2024-01-14 06:35 UTC, AziatAbd commented on src/components/UI/Input/Input.jsx
> +      width: '26rem',
100% сделайте

2024-01-14 06:35 UTC, AziatAbd commented
![image](https://github.com/peaksoft-school/health-check-js11/assets/115453436/951904c0-2a74-4383-9ed2-cc791dabd9cf)
Разве в select можно писать? Исправьте

2024-01-14 06:36 UTC, AziatAbd commented
![image](https://github.com/peaksoft-school/health-check-js11/assets/115453436/51164f26-eb55-49b0-a716-0b48e6f51ecf)

label стал белым при active

2024-01-14 06:37 UTC, AziatAbd commented
![image](https://github.com/peaksoft-school/health-check-js11/assets/115453436/15f46ec3-b2ff-4584-9da3-ab8b6f74b062)

папку и файл поменяйте на Select

2024-01-16 15:25 UTC, Nuranazm commented on src/components/UI/Input/Input.jsx
> +      width: '26rem',
кичинекей болуп калат экен px кылдым

2024-01-16 15:25 UTC, Nuranazm commented on src/components/UI/Input/Input.jsx
> +      { value, onChange, placeholder, invalid, error, type = 'text', ...rest },
удалила

2024-01-17 10:40 UTC, AziatAbd commented
![image](https://github.com/peaksoft-school/health-check-js11/assets/115453436/7a15ee84-e864-41fd-8862-af0903552d57)

Label куда-то поплыла

2024-01-17 10:46 UTC, AziatAbd requested changes

2024-01-17 10:46 UTC, AziatAbd commented on src/components/UI/Input/Input.jsx
> +      width: '414px',
я имел виду width: 100%, а height можно не трогать

2024-01-17 10:46 UTC, AziatAbd commented on src/components/UI/select/Select.jsx
> +const Selector = forwardRef(({ options, onChange, ...rest }, ref) => {
переименуйте в Select

2024-01-17 10:46 UTC, AziatAbd commented
![image](https://github.com/peaksoft-school/health-check-js11/assets/115453436/aca4781e-0cd0-4caf-9470-f4a05ee03d81)

что с размером option?

2024-01-22 04:03 UTC, merged