Feature/our services
peaksoft-school/health-check-js11 pull request #16
Opened 2024-01-15 11:03 UTC by BayturPS

2024-01-15 11:34 UTC, Bermet001 commented on src/components/OurServices.jsx
> +import React from 'react'
удали

2024-01-15 11:34 UTC, Bermet001 commented on src/utils/constants/our-services.js
> +export const services = [
CAMEL CASE

2024-01-17 06:27 UTC, AziatAbd requested changes

2024-01-17 06:27 UTC, AziatAbd commented on src/utils/constants/our-services.js
camelCase

2024-01-17 06:28 UTC, AziatAbd commented
для каждой страницы должна быть отдельная папка, а то запутаешься. Откройте папку landing-page и переместите туда нужные файлы

2024-01-17 10:49 UTC, AziatAbd requested changes

2024-01-17 10:49 UTC, AziatAbd commented on src/App.jsx
>  }
верни App

2024-01-17 12:35 UTC, merged