Feature/best doctors
peaksoft-school/health-check-js11 pull request #17
Opened 2024-01-15 11:46 UTC by Nuranazm

2024-01-15 12:13 UTC, BayturPS commented on src/components/BestDoctors/BestDoctors.jsx
> +import React from 'react'
import React from 'react' удалите

2024-01-15 12:13 UTC, BayturPS commented on src/components/BestDoctors/BestDoctors.jsx
> +                  {/* </DoctorCard> */}
удалите комменты

2024-01-15 12:13 UTC, BayturPS commented on src/components/BestDoctors/BestDoctors.jsx
> +   fontFamily: 'Manrope',
font family index css де бар удалите

2024-01-15 12:13 UTC, BayturPS commented on src/components/UI/Button.jsx
> +   variant = '',
variant = '' cделайте просто вариант без = ' ',

2024-01-15 12:13 UTC, BayturPS commented on src/utils/constants/index.js
> +export const infoDoctors = [
CAMEL CASE  SNAKE CASE

2024-01-15 12:13 UTC, BayturPS commented on src/utils/constants/index.js
> +import fifth from '../../assets/images/Exclude.png'
logicial names for images

2024-01-17 06:35 UTC, AziatAbd commented
![image](https://github.com/peaksoft-school/health-check-js11/assets/115453436/977ad846-e020-420d-bd47-b3663c53f0d4)

исправьте ошибки

2024-01-17 06:40 UTC, AziatAbd commented
![image](https://github.com/peaksoft-school/health-check-js11/assets/115453436/cfaa1a4c-5165-4a2c-8b4c-515e4dbe08e2)
переместите картинки по центру, и внимательно посмотрите на ваши картинки и те что в фигме. Фотка Мисько Екатерина прям идеально стоит, а другие уже поплыли

2024-01-17 06:43 UTC, AziatAbd requested changes

2024-01-17 06:43 UTC, AziatAbd commented on src/components/whyWe/Why-we.jsx
просто WhyWe без "-". И я так понимаю ваш второй таск тоже здесь?

2024-01-17 06:43 UTC, AziatAbd commented on src/components/UI/Button.jsx
> +
из-за этого выходит ошибка в компоненте

2024-01-17 12:48 UTC, AziatAbd requested changes

2024-01-17 12:48 UTC, AziatAbd commented on src/components/BestDoctors/BestDoctors.jsx
> +               </Grid>
className не нужны, используйте styled

2024-01-17 12:48 UTC, AziatAbd commented on src/components/BestDoctors/BestDoctors.jsx
> +                     <img className="img" src={image} alt="hdhal" />
дайте img свойство       objectFit: 'contain',

2024-01-17 12:48 UTC, AziatAbd commented on src/components/BestDoctors/BestDoctors.jsx
> +               </Grid>
также карточки должны быть кликабельны

2024-01-22 04:26 UTC, AziatAbd commented
![image](https://github.com/peaksoft-school/health-check-js11/assets/115453436/22f6a229-376a-4a99-8e94-b826b036b9eb)
У меня получилось сделать их круглыми. Теперь попробуйте вы, а то они овальные у вас
![image](https://github.com/peaksoft-school/health-check-js11/assets/115453436/1d3b5c08-bcfd-4e12-a421-628432a6c2f6)

2024-01-22 08:00 UTC, merged