Feature/modal
peaksoft-school/health-check-js11 pull request #26
Opened 2024-01-24 05:52 UTC by BayturPS

2024-01-24 06:58 UTC, Bermet001 commented on src/components/UI/Modal.jsx
> +import { styled } from '@mui/material'
import { styled,Slide, DialogContent, Dialog  } from '@mui/material'

2024-01-24 06:58 UTC, Bermet001 commented on src/components/UI/Modal.jsx
> +                  <CloseIcon />
можно же сразу иконке дать onClick

2024-01-24 06:58 UTC, Bermet001 commented on src/components/UI/Modal.jsx
> +   '& .css-1t1j96h-MuiPaper-root-MuiDialog-paper': {
не стилизуй с помощью таких классов

2024-01-25 13:12 UTC, BayturPS commented on src/components/UI/Modal.jsx
> +                  <CloseIcon />
я специально

2024-01-25 13:14 UTC, BayturPS commented on src/components/UI/Modal.jsx
> +   '& .css-1t1j96h-MuiPaper-root-MuiDialog-paper': {
> не стилизуй с помощью таких классов

без этого никак

2024-01-25 13:14 UTC, BayturPS commented on src/components/UI/Modal.jsx
> +                  <CloseIcon />
> можно же сразу иконке дать onClick

я специально

2024-01-26 05:21 UTC, Bermet001 commented on src/components/UI/Modal.jsx
> +   },
зачем здесь использовать псевдокласс?

2024-01-26 05:21 UTC, Bermet001 commented on src/components/UI/Modal.jsx
> +      width: '100$',
что за знак валюты? убери или же замени

2024-01-26 05:21 UTC, Bermet001 commented on src/components/UI/Modal.jsx
> +   // open - is state
убери коменты

2024-01-26 11:51 UTC, AziatAbd requested changes

2024-01-26 11:51 UTC, AziatAbd commented on src/components/UI/Modal.jsx
> +   },
cursor: pointer можно дать не используя hovera

2024-01-26 15:57 UTC, merged